---
name: livecare
description: A new Flutter project.
publish_to: none
version: 4.0.17+60
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  package_info_plus: "^4.0.0"
  google_maps_flutter: "^2.0.6"
  fluttertoast: "^8.0.7"
  shared_preferences: "^2.0.6"
  http: "^0.13.3"
  timezone: "^0.8.0"
  intl: "^0.18.0"
  cupertino_icons: "^1.0.2"
  sticky_headers: "^0.2.0"
  flutter_picker: "^2.1.0"
  syncfusion_flutter_signaturepad: "^19.2.44"
  image_picker: "^0.8.1+3"
  webview_flutter: "^2.0.9"
  path_provider: "^2.0.2"
  google_place: "^0.4.0"
  url_launcher: "^6.1.10"
  flutter_polyline_points: "^1.0.0"
  rxdart: "^0.27.1"
  location: "^5.0.0"
  photo_view: "^0.14.0"
  socket_io_client: "^1.0.1"
  connectivity_plus: "^1.0.7"
  firebase_analytics: "^10.4.2"
  firebase_crashlytics: "^3.3.2"
  firebase_messaging: "^14.6.2"
  firebase_core: "^2.13.1"
  firebase_database: "^10.2.2"
  permission_handler: "^10.2.0"
  cloud_firestore: "^4.8.0"
  cloud_firestore_web: "^3.6.0"
  flutter_plugin_android_lifecycle: "^2.0.15"
  flutter_dotenv: "^5.0.2"
  flutter_svg: "^1.1.6"
  auth0_flutter: "^1.1.0"
  get: "^4.6.5"
  awesome_dio_interceptor: "^0.0.2+4"
  dio: "^4.0.6"
  geocoding: "^2.1.0"
  geocoder2: "^1.0.4"
  new_version: "^0.3.1"
  local_auth: "^2.1.7"
dependency_overrides:
  package_info_plus: "^4.0.1"
  wakelock_windows: any
  win32: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: "^4.8.0"
  flutter_lints: "^1.0.0"
  test: "^1.16.8"
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - ".env"
  fonts:
  - family: Lato
    fonts:
    - asset: assets/fonts/lato_regular.ttf
    - asset: assets/fonts/lato_bold.ttf
      weight: 700
